apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase
  template:
    metadata:
      labels:
        app: couchbase
    spec:
      containers:
        - name: couchbase
          image: couchbase:latest
          env:
            - name: COUCHBASE_ADMINISTRATOR_USERNAME
              value: "admin"
            - name: COUCHBASE_ADMINISTRATOR_PASSWORD
              value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: couchbase-service
spec:
  selector:
    app: couchbase
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: ClusterIP
