apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
        - name: microservice
          image: acquireinc/pdqa:microservices
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKER_HOST
              value: "kafka-service:9092"
            - name: ZOOKEEPER_HOST_URL
              value: "kafka-service:2181"
            - name: DB_URL
              value: "couchbase-service"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: microservice-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microservice-secret
                  key: DB_PASSWORD

      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-service
spec:
  selector:
    app: microservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
