apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kafka-test
resources:
  - zookeeper.yaml
  - kafka-statefulset.yaml
  # - kafka-ui.yaml
  - kcat.yaml
  - persistent-volume.yaml
