apiVersion: v1
kind: PersistentVolume
metadata:
  name: pdqa-kafka-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kafka"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pdqa-zookeeper-data-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/zookeeper/data"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pdqa-zookeeper-logs-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/zookeeper/logs"