apiVersion: apps/v1
kind: StatefulSet
metadata: 
  labels:
    service: zookeeper
  name: zookeeper
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      service: zookeeper
  template:
    metadata:
      labels: 
    #     network/kafka-network: "true"
        service: zookeeper
    spec:
      securityContext:
        fsGroup: 1000
      enableServiceLinks: false
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.3.2
        ports: 
          - containerPort: 2182
        env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2182"
          - name: ZOOKEEPER_DATA_DIR
            value: "/var/lib/zookeeper/data"
          - name: ZOOKEEPER_LOG_DIR
            value: "/var/lib/zookeeper/log"
          - name: ZOOKEEPER_SERVER_ID
            value: "1"
        volumeMounts:
          - mountPath: /var/lib/zookeeper/data
            name: zookeeper-data
          - mountPath: /var/lib/zookeeper/log
            name: zookeeper-logs
      hostname: zookeeper
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-data
      spec:
        volumeName: pdqa-zookeeper-data-pv-volume
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

    - metadata:
        name: zookeeper-logs
      spec:
        volumeName: pdqa-zookeeper-logs-pv-volume
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  labels:
    service: zookeeper
  name: zookeeper
spec:
  ports:
    - name: "2182"
      port: 2182
      targetPort: 2182
  selector:
    service: zookeeper
