apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdqa-app-ingress
  annotations:
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - cd.nust.na
    secretName: tls-secret
  rules:
  - host: cd.nust.na
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: pdqa-frontend-service
              port:
                number: 80
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: pdqa-backend-service
              port:
                number: 80
