apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdqa-app-ingress
spec:
  rules:
    - host: dev.pdqa
      http:
        paths:
          # - path: /
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: frontend-service
          #       port:
          #         number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: pdqa-backend-service
                port:
                  number: 4931
