apiVersion: v1
kind: Secret
metadata:
  name: pdqa-db-auth
type: Opaque
data:
  username: YWRtaW4= # admin
  password: cGFzc3dvcmQ=         # password

---

apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: yester-curricula-dev

---

apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: yester-need-analyses

---

apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: yester-need-curricula-dev

---

apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: yester-programmes

---

apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: yester-users

---

apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: pdqa-db-cluster
spec:
  image: couchbase/server:7.6.0
  security:
    adminSecret: pdqa-db-auth
  networking:
    exposeAdminConsole: true
    adminConsoleServices:
    - data
  buckets:
    managed: true
  servers:
  - size: 1
    name: all_services
    services:
    - data
    - index
    - query
    - search
    - eventing
    - analytics