apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdqa-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pdqa-frontend
  template:
    metadata:
      labels:
        app: pdqa-frontend
    spec:
      containers:
        - name: pdqa-frontend
          image: my-frontend
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: pdqa-frontend-service
spec:
  selector:
    app: pdqa-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
