apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdqa-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdqa-frontend
  template:
    metadata:
      labels:
        app: pdqa-frontend
    spec:
      containers:
        - name: pdqa-frontend
          image: ghcr.io/curiapp/lasta-hub/pdqa-frontend
          ports:
            - containerPort: 4000

      # imagePullSecrets:
      #   - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: pdqa-frontend-service
spec:
  selector:
    app: pdqa-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer
