apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: pdqa-develop
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "Pelema",
          "password": "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"
        }
      }
    } 