apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: pdqa-develop
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "curiapp",
          "password": "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"
        }
      }
    } 