apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdqa-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdqa-microservices
  template:
    metadata:
      labels:
        app: pdqa-microservices
    spec:
      containers:
        - name: pdqa-microservices
          image: ghcr.io/curiapp/curdev/pdqa-microservices
          # ports:
          #   - containerPort: 8080
          env:
            - name: KAFKA_BROKER_HOST
              value: "196.216.167.190:9092"
            - name: ZOOKEEPER_HOST_URL
              value: "196.216.167.190:2181"
            - name: DB_URL
              value: "196.216.167.190"
            - name: DB_USER
              value: "admin"
              # valueFrom:
              #   secretKeyRef:
              #     name: pdqa-microservices-secret
              #     key: DB_USER
            - name: DB_PASSWORD
              value: "password"
              # valueFrom:
              #   secretKeyRef:
              #     name: pdqa-microservices-secret
              #     key: DB_PASSWORD

      # imagePullSecrets:
      #   - name: ghcr-secret
