apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdqa-microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pdqa-microservices
  template:
    metadata:
      labels:
        app: pdqa-microservices
    spec:
      containers:
        - name: pdqa-microservices
          image: ghcr.io/pelema/lasta-hub
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKER_HOST
              value: "kafka-service:9092"
            - name: ZOOKEEPER_HOST_URL
              value: "kafka-service:2181"
            - name: DB_URL
              value: "couchbase-service"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: pdqa-microservices-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pdqa-microservices-secret
                  key: DB_PASSWORD

      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: pdqa-microservice-service
spec:
  selector:
    app: pdqa-microservices
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
